name: Pedantic check

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: apt-get update
        run:  sudo apt-get update
      - name: Install dependencies
        run:  sudo apt-get install -y automake autoconf
      - name: Pedantic check
        run: ./extra/pedantic.sh
